site_name: Code2025

theme:
  name: material
  features:
    - navigation.tabs
  language: zh

nav:
  - Home: index.md
  - Lab0:
    - Guidance: lab0/guidance.md
    - Solution: lab0/solution.md
  - Lab1:
    - Guidance: lab1/guidance.md
    - Solution: lab1/solution.md
  - Lectures:
    - Lecture 1: lectures/lecture1 - 张逸安.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

plugins:
  - glightbox:
       touchNavigation: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
