site_name: Code2025

theme:
  name: material
  features:
    - navigation.tabs
  language: zh

nav:
  - Home: index.md
  - Lab0: lab0.md
  - Lab1: lab1.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - glightbox:
       touchNavigation: true
