site_name: Code2025

theme:
  name: material
  features:
    - navigation.tabs
  language: zh

nav:
  - Home: index.md
  - Lab0: lab0.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

plugins:
  - glightbox:
       touchNavigation: true
